language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ouCFmamuKGCW91zYS4pRAiKq5Ty0j6k/0GtWF83+ggF/qU2lP8oCYO6XWgjZGpGddev00XZjBGC3B/KsTne2Kfsl8QKaGhX2VcJ7qRr0FzM6k0O64O0IpEVbXUGEBSNsiwoujGT4IHtSPGvzXI5zvGCdFyuvezgU771YPcD3379xO8WbjxVdZ1POwgLHh3afr6cNxLMbCOvV4aGuUSZnzVYOlWtN3iEwSnAGozXj8F2of55BG0/K+VymUeqb+RlRJ4dUySXRUBBnWnrS/kK888FhBVlsSEBmgG3U1qlZI7vzdrfkUnAGp8FO/YjdSEwZbzXa73AszKOpDxpQ+3/6uGPZZbpGq/b5yuCPWvllnWu0M7+80DYbDs7aVbk2OtyZrh5yUSJUl+uh+GPS0C0pUXfpZKM90OSq0rpqDweW0JzCdAZ+8h0Kmd/mIzmrL/TZKIjvS9ptSW03gonVbOLHP2StHKD9uuVRZqyzoYGb/h3t3lzoBhdWqus/pL7JQ4XQ32MXS1FoAI2unF4/JLEK3feSOfQvPa3sEjMYCI5PaWol/RstKBqa2i24UGXBhDlPLErGa+H5KhsdLaEbpOMDJ7xbQLNPGjmKlo0FQI6zmeufqhhvgIxZ52rNwqsIAn5REXH58WYeIOv0mPDRLv9oAT9gCNwh+SDLV3J21Gy6Qys=
  app: aqueous-inlet-15627
  on:
    repo: TreyLiebscher/storyBank
